services:
    access:
        container_name: access-service
        build:
            context: .
            target: development
            args:
                USER_ID: ${UID:-1000}
                GROUP_ID: ${GID:-1000}
            dockerfile: ./.docker/access/Dockerfile
        volumes:
            - ./access:/var/www/html
        networks:
            - main_network
        depends_on:
            - access-mongo

    access-mongo:
        container_name: access-mongo-db
        image: mongodb/mongodb-community-server:8.0-ubi9
        networks:
            - main_network
        volumes:
            - "mongodb:/data/db"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
        ports:
            - "27017:27017"

    nginx:
        container_name: nginx-telemetry
        image: nginx:latest
        ports:
            - "8020:80"
        volumes:
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - main_network
        depends_on:
            - access

    normalization:
        container_name: normalization-service
        build:
            context: .
            dockerfile: ./.docker/normalization/Dockerfile
        volumes:
            - ./normalization:/var/www/html
        ports:
            # - "49152–65535:49152–65535/udp" (Max ephemeral range)
            - "60000-60500:60000-60500/udp"
        networks:
            - main_network

    kafka:
        image: apache/kafka:4.1.0
        container_name: kafka-telemetry
        build:
            context: .
        ports:
            - "9092:9092"
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092"
            KAFKA_PROCESS_ROLES: "broker,controller"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:29093"
            KAFKA_LISTENERS: "CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092"
            KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
            KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
        networks:
            - main_network

    scylla:
        image: scylladb/scylla:2025.3
        container_name: scylla-telemetry
        volumes:
            - scylla:/var/lib/scylla
        networks:
            - main_network

networks:
    main_network:
        driver: bridge

volumes:
    mongodb:
        driver: local
    scylla:
        driver: local
