services:
  access:
    container_name: access-service
    build: 
      context: .
      target: development
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
      dockerfile: ./.docker/access/Dockerfile
    volumes:
      - ./access:/var/www/html
    networks:
      - main_network
    depends_on:
      - access-mongo

  access-mongo:
    container_name: access-mongo-db
    image: mongodb/mongodb-community-server:8.0-ubi9
    networks:
        - main_network
    volumes:
        - 'mongodb:/data/db'
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
        - "27017:27017"

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
        - main_network
    depends_on:
        - access-service
    
networks:
  main_network:
    driver: bridge

volumes:
  mongodb:
    driver: local